name: Build & Release mpy Package To Github

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip

      - name: Clone and build mpy-cross
        run: |
          git clone https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init lib/* ports/unix
          make -C mpy-cross
          cp mpy-cross/build/mpy-cross ../../mpy-cross  # move binary up a level
  
      - name: Compile senko and mrequests to mpy
        run: |
          mkdir -p build
          ./micropython/mpy-cross/build/mpy-cross slick-ota/slick-ota.py -o build/slickota.mpy
          ./micropython/mpy-cross/build/mpy-cross slick-ota/mrequests.py -o build/mrequests.mpy

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.mpy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit compiled files
        run: |
          git add build/*.mpy
          git commit -m "Auto-commit compiled .mpy files [ci skip]" || echo "No changes to commit"
          git push origin HEAD:master  # change 'main' if using another branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
